server:
  port: 8888
encrypt:
  key: MIIBITANBgkqhkiG9w0BAQEFAAOCAQ4AMIIBCQKCAQB1SijU/KR0BmTDuvJfOpt/3lA9gMaL+qXrHNEjcQCEvDkTrNSmyG4NUvkP0B34A3FUZLEPNQ8meY8IZYiN0krh+lDJvVfAmOYCzNFzqzvwCzAK4FaH1AHVvPqQ85R8PJ4go0Ob7pBVIpYBNhSXhgIh6hUakLzN7Kh8vPWlXwKIUUObQWEwnP4Bw9TORG2Mqor7iLsq43KDIpvBiw676En9KnZ6dR5UNWMfjgTrgW0DXztsbWlCytoYk0jyJv6E7VmbEQhpoNQ3uhMiEUkxxOBJzzSa8uhHNkFIw3rg6aCF72iO3HuxIJt9OEkFsitEuA0NEvZWxa47onl+Y/hYT37BAgMBAAE=
spring:
  security:
    user:
      name: nondefaultusername
      password: 3606ed88-0b68-4db3-bd5a-8b032e11918f
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tomaskul/spring-cloudconfig-course-tolls
          search-paths:
            - station*